### ISSUE TITLE
Display a User Friendly Message Instead of Error 500

### ISSUE THREAD

**Issue by NigelRodgers** [NigelRodgers/camptix-paynow#2]
In classes/class-camptix-payment-method-paynow.php on line 203 instead of throwing an exception and causing error 500, display the message in the exception to the user. In other words display a user friendly message instead of causing the site to break after failure to connect to PayNow.

**Comment by glueckpress** [comment]
Actual section for reference:

https://github.com/NigelRodgers/camptix-paynow/blob/3b5f6356013075c2a4a2679429507b27323da71a/classes/class-camptix-payment-method-paynow.php#L200-L205

**Comment by schlessera** [comment]
I can only guess by what I'm seeing in the CampTix code, as I have never worked on that system myself, but what I see lets me make the following observations:

- The checkout method states that it should return an `int` value with the payment status: https://github.com/Automattic/camptix/blob/master/inc/class-camptix-payment-method.php#L209-L216 . So, the `return` should probably adhere to that.
- There's a method called `payment_result()` you can use to store the status of this payment for the attendee: https://github.com/Automattic/camptix/blob/master/camptix.php#L7035 . This might or might not send an email to the attendee to let them know.
- I'm not sure how the `payment_result()` data is actually used on the frontend. It might be displayed, or it might not. If it is not and your checkout method actually has control over the HTML sent to the browser, then you can create a short piece of HTML to display the error that was produced to the user.

Hope this helps!

**Comment by NigelRodgers** [comment]
Thank you @schlessera! Found it! I tried replacing the exception with the following and it worked!

`return $this->payment_result($payment_token, CampTix_Plugin::PAYMENT_STATUS_FAILED);`

I'll pass it on to one of our local devs so they can code it out properly.

**Comment by lenos2** [comment]
> Actual section for reference:
> 
> [camptix-paynow/classes/class-camptix-payment-method-paynow.php](https://github.com/NigelRodgers/camptix-paynow/blob/3b5f6356013075c2a4a2679429507b27323da71a/classes/class-camptix-payment-method-paynow.php#L200-L205)
> 
> Lines 200 to 205 in [3b5f635](/NigelRodgers/camptix-paynow/commit/3b5f6356013075c2a4a2679429507b27323da71a)
> 
>          if ( is_wp_error( $remote_response ) ) { 
>             $error_message = $remote_response->get_error_message(); 
>             $this->log(sprintf("Remote Request failed:" . $error_message . ': %s', null, "failed_request")); 
>             throw new \Exception("There was a problem connecting to the PayNow Gateway. Please try again later. If the problem persists please contact the website admin. /nDetails:/n" . $error_message); 
>              //$this->log(sprintf("Remote Request failed:" . $error_message . ': %s', null, $payload)); 
>          } else {

I have added a modal method to display a friendly message to the user. Thanks

**Comment by lenos2** [comment]
> I can only guess by what I'm seeing in the CampTix code, as I have never worked on that system myself, but what I see lets me make the following observations:
> 
> * The checkout method states that it should return an `int` value with the payment status: https://github.com/Automattic/camptix/blob/master/inc/class-camptix-payment-method.php#L209-L216 . So, the `return` should probably adhere to that.
> * There's a method called `payment_result()` you can use to store the status of this payment for the attendee: https://github.com/Automattic/camptix/blob/master/camptix.php#L7035 . This might or might not send an email to the attendee to let them know.
> * I'm not sure how the `payment_result()` data is actually used on the frontend. It might be displayed, or it might not. If it is not and your checkout method actually has control over the HTML sent to the browser, then you can create a short piece of HTML to display the error that was produced to the user.
> 
> Hope this helps!

I Added the return statements returning the appropriate results. Thanks
As for showing messages to the user, I think the modal I added should do the trick

**Comment by NigelRodgers** [comment]
I've updated the plugin and am awaiting approval. Thanks for the support everyone!

**Comment by NigelRodgers** [comment]
Lucia and Lance from PayNow also suggested using try/catch blocks and creating an error variable or object similar to payment_result()  I'm just adding the idea here as a comment for future reference.

I'll close this issue for now.
